In [1]:
import pandas as pd
import numpy as np

from movie import load_movie
from model import HME

from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [2]:
x_train, x_test, y_train, y_test = load_movie('train', data_limit=5000, train_ratio=0.8)

In [3]:
x_train.shape

(4000, 5879)

In [24]:
n_feature = x_train.shape[1]
n_level = 2

n_expert1 = 4
n_expert2 = 4

hme = HME(n_feature, n_expert1, n_expert2, n_level, 
          batch_size=64,
          lr=1., l1_coef=0.0001, l21_coef=0.0001,
          algo='fista')

In [25]:
print((hme.predict(x=x_train)==y_train).mean())
confusion_matrix(hme.predict(x=x_train), y_train)

0.48375


array([[ 813,  823],
       [1242, 1122]])

In [26]:
max_iter = 10000
stop_thre = 3

hme.fit(x_train, y_train, max_iter=max_iter, stop_thre=stop_thre, log_interval=max_iter // 50)

[accu: 0.9295], [loss: 19.230246793347895], [nllk: 0.2651913002330248]
[accu: 0.93575], [loss: 70.84243434133488], [nllk: 0.2793930445689668]
[accu: 0.9525], [loss: 84.51247505432373], [nllk: 0.2508994527397308]
[accu: 0.95775], [loss: 111.61420209873394], [nllk: 0.24354183752713437]
[accu: 0.96025], [loss: 133.7696611931432], [nllk: 0.23946407825119148]
[accu: 0.9595], [loss: 151.14947986460461], [nllk: 0.2412025060119526]
[accu: 0.96025], [loss: 176.84518927968693], [nllk: 0.24157154368975164]
[accu: 0.9615], [loss: 204.04148780139434], [nllk: 0.2434251596432967]
[accu: 0.9625], [loss: 223.8392343382666], [nllk: 0.24175319193689127]
[accu: 0.9635], [loss: 246.9923710455344], [nllk: 0.24107187053112467]
[accu: 0.96325], [loss: 263.35980951470424], [nllk: 0.23936287250461563]
[accu: 0.96475], [loss: 285.2422620469878], [nllk: 0.2399725578288706]
[accu: 0.9615], [loss: 308.0098477713177], [nllk: 0.24394355478502905]
[accu: 0.9645], [loss: 325.9855612429263], [nllk: 0.2391635144548572]
[

print((hme.predict(x=x_train)==y_train).mean())
confusion_matrix(y_train, hme.predict(x=x_train))

In [28]:
print((hme.predict(x=x_test)==y_test).mean())
confusion_matrix(y_test, hme.predict(x=x_test))

0.829


array([[442,  85],
       [ 86, 387]])

# Decision Tree

In [44]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(max_depth=4)
dt.fit(x_train, y_train.ravel())

DecisionTreeClassifier(max_depth=4)

In [45]:
y_pred = dt.predict(x_train)
y_real = y_train.ravel()

print((y_pred==y_real).mean())
confusion_matrix(y_real, y_pred)

0.68175


array([[ 978, 1077],
       [ 196, 1749]])

In [46]:
y_pred = dt.predict(x_test)
y_real = y_test.ravel()

print((y_pred==y_real).mean())
confusion_matrix(y_real, y_pred)

0.656


array([[243, 284],
       [ 60, 413]])

# Unconstrained DT

In [4]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(x_train, y_train.ravel())

DecisionTreeClassifier()

In [5]:
y_pred = dt.predict(x_train)
y_real = y_train.ravel()

print((y_pred==y_real).mean())
confusion_matrix(y_real, y_pred)

1.0


array([[2047,    0],
       [   0, 1953]])

In [6]:
y_pred = dt.predict(x_test)
y_real = y_test.ravel()

print((y_pred==y_real).mean())
confusion_matrix(y_real, y_pred)

0.661


array([[357, 178],
       [161, 304]])

In [32]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(max_depth=4)
rf.fit(x_train, y_train.ravel())

RandomForestClassifier(max_depth=4)

In [33]:
y_pred = rf.predict(x_train)
y_real = y_train.ravel()

print((y_pred==y_real).mean())
confusion_matrix(y_real, y_pred)

0.82875


array([[1869,  186],
       [ 499, 1446]])

In [34]:
y_pred = rf.predict(x_test)
y_real = y_test.ravel()

print((y_pred==y_real).mean())
confusion_matrix(y_real, y_pred)

0.79


array([[469,  58],
       [152, 321]])

# Unconstrained RF

In [7]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(x_train, y_train.ravel())

RandomForestClassifier()

In [8]:
y_pred = rf.predict(x_train)
y_real = y_train.ravel()

print((y_pred==y_real).mean())
confusion_matrix(y_real, y_pred)

1.0


array([[2047,    0],
       [   0, 1953]])

In [9]:
y_pred = rf.predict(x_test)
y_real = y_test.ravel()

print((y_pred==y_real).mean())
confusion_matrix(y_real, y_pred)

0.811


array([[453,  82],
       [107, 358]])