In [17]:
import pandas as pd
import numpy as np

from movie import load_movie
from model import HME

from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [18]:
x_train, x_test, y_train, y_test = load_movie('train', data_limit=5000, train_ratio=0.8)

In [20]:
x_train.shape

(4000, 5879)

In [50]:
n_feature = x_train.shape[1]
n_level = 2

n_expert1 = 4
n_expert2 = 4

hme = HME(n_feature, n_expert1, n_expert2, n_level, 
          batch_size=64,
          lr=1., l1_coef=0.001, l21_coef=0.001,
          algo='fista')

In [51]:
print((hme.predict(x=x_train)==y_train).mean())
confusion_matrix(hme.predict(x=x_train), y_train)

0.4905


array([[ 828,  811],
       [1227, 1134]])

In [52]:
max_iter = 10000
stop_thre = 3

hme.fit(x_train, y_train, max_iter=max_iter, stop_thre=stop_thre, log_interval=max_iter // 50)

[accu: 0.8405], [loss: 238.7313754109688], [nllk: 0.41603470149257066]
[accu: 0.822], [loss: 743.610363029733], [nllk: 0.48080241702432025]
[accu: 0.82325], [loss: 1212.5539655831633], [nllk: 0.4984524489401133]
[accu: 0.82325], [loss: 1724.0699457166288], [nllk: 0.48599468015621167]
[accu: 0.84225], [loss: 1999.9930961004195], [nllk: 0.40287905889492837]
[accu: 0.8235], [loss: 2463.152891942818], [nllk: 0.4816103567426802]
[accu: 0.83], [loss: 3225.82964651994], [nllk: 0.4367771267075806]
[accu: 0.83225], [loss: 3828.643338929811], [nllk: 0.451551141707935]
[accu: 0.8275], [loss: 4555.814224600572], [nllk: 0.4956330469048567]
stop increasing accuracy at iter: 1800


In [53]:
print((hme.predict(x=x_train)==y_train).mean())
confusion_matrix(y_train, hme.predict(x=x_train))

0.8275


array([[1660,  395],
       [ 295, 1650]])

In [54]:
print((hme.predict(x=x_test)==y_test).mean())
confusion_matrix(y_test, hme.predict(x=x_test))

0.791


array([[416, 111],
       [ 98, 375]])